# Generated by Django 4.2.2 on 2023-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('guitar_type', models.CharField(choices=[('CL', 'Classical'), ('EL', 'Electric'), ('AC', 'Acoustic'), ('BA', 'Bass')], max_length=2)),
                ('finish', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_production', models.IntegerField(blank=True, null=True)),
                ('frets', models.CharField(blank=True, max_length=100, null=True)),
                ('is_right_handed', models.BooleanField(default=True)),
                ('body_type', models.CharField(blank=True, choices=[('SE', 'Semi hollow body'), ('HO', 'Hollow body'), ('SO', 'Solid body')], max_length=2, null=True)),
                ('fretboard_material', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_string', models.CharField(max_length=100)),
                ('neck_material', models.CharField(blank=True, max_length=100, null=True)),
                ('body_material', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_configuration', models.CharField(choices=[('H', 'Humbucker'), ('HH', 'Two humbuckers'), ('HHH', 'Three humbuckers'), ('S', 'Singlecoil'), ('SS', 'Two singlecoils'), ('SSS', 'Three singlecoils'), ('HS', 'Humbucker + Singlecoil'), ('HSS', 'Humbucker + two singlecoils')], max_length=3)),
                ('bridge_type', models.CharField(choices=[('FI', 'Fixed bridge'), ('TR', 'Tremolo bridge')], max_length=2)),
            ],
        ),
    ]
