# Generated by Django 4.2.2 on 2023-07-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='condition',
            field=models.CharField(choices=[('EXC', 'Excellent condition'), ('VGO', 'Very good condition'), ('GOO', 'Good condition'), ('FAI', 'Faris condition'), ('POR', 'Poor condition')], default='EXC', max_length=3),
        ),
    ]
