# Generated by Django 4.2.2 on 2023-07-01 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear', '0002_guitar_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcousticGuitarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Acoustic Guitar',
                'verbose_name_plural': 'Acoustic Guitars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gear.guitar',),
        ),
        migrations.CreateModel(
            name='BassGuitarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bass Guitar',
                'verbose_name_plural': 'Bass Guitars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gear.guitar',),
        ),
        migrations.CreateModel(
            name='ClassicalGuitarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Classical Guitar',
                'verbose_name_plural': 'Classical Guitars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gear.guitar',),
        ),
        migrations.CreateModel(
            name='ElectricGuitarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Electric Guitar',
                'verbose_name_plural': 'Electric Guitars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gear.guitar',),
        ),
        migrations.AddField(
            model_name='guitar',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='condition',
            field=models.CharField(choices=[('EXC', 'Excellent condition'), ('VGO', 'Very good condition'), ('GOO', 'Good condition'), ('FAI', 'Fair condition'), ('POR', 'Poor condition')], default='EXC', max_length=3),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='is_right_handed',
            field=models.BooleanField(default=True, verbose_name='Right handed'),
        ),
    ]
