# Generated by Django 4.2.2 on 2023-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_acousticguitarproxy_bassguitarproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='transaction_type',
            field=models.CharField(choices=[('SEL', 'Sell'), ('EXC', 'Exchange'), ('REN', 'Rent')], default='SEL', max_length=3),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='pickup_configuration',
            field=models.CharField(choices=[('H', 'Humbucker'), ('HH', 'Two humbuckers'), ('HHH', 'Three humbuckers'), ('S', 'Singlecoil'), ('SS', 'Two singlecoils'), ('SSS', 'Three singlecoils'), ('HS', 'Humbucker + Singlecoil'), ('HSS', 'Humbucker + two singlecoils'), ('OTH', 'Other'), ('NON', 'No pickups')], max_length=3),
        ),
    ]
