# Generated by Django 4.2.2 on 2023-07-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_guitar_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
