# Generated by Django 4.2.2 on 2023-07-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_alter_guitar_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar',
            old_name='number_of_string',
            new_name='number_of_strings',
        ),
    ]
