# Generated by Django 4.2.2 on 2023-07-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_rename_number_of_string_guitar_number_of_strings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('more_info', models.TextField(verbose_name='More informations')),
                ('related_gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_for', to='gear.guitar')),
            ],
        ),
    ]
