# Generated by Django 4.2.2 on 2023-07-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0009_remove_guitar_price_sell_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='guitar',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='gear.image'),
        ),
    ]
