# Generated by Django 4.2.2 on 2023-07-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0010_image_guitar_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='images',
            field=models.ManyToManyField(blank=True, to='gear.image'),
        ),
    ]
