# Generated by Django 4.2.2 on 2023-07-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0011_alter_guitar_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='guitar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.guitar'),
        ),
    ]
