# Generated by Django 4.2.2 on 2023-07-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0012_remove_guitar_images_image_guitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
