# Generated by Django 4.2.2 on 2023-07-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0013_exchange_title_rent_title_sell_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
