# Generated by Django 4.2.2 on 2023-07-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0014_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='title',
        ),
    ]
