# Generated by Django 4.2.2 on 2023-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0015_remove_exchange_title_remove_rent_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
