# Generated by Django 4.2.2 on 2023-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0017_alter_exchange_brand_alter_exchange_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='bridge_type',
            field=models.CharField(blank=True, choices=[('FI', 'Fixed bridge'), ('TR', 'Tremolo bridge')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='number_of_strings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='pickup_configuration',
            field=models.CharField(blank=True, choices=[('H', 'Humbucker'), ('HH', 'Two humbuckers'), ('HHH', 'Three humbuckers'), ('S', 'Singlecoil'), ('SS', 'Two singlecoils'), ('SSS', 'Three singlecoils'), ('HS', 'Humbucker + Singlecoil'), ('HSS', 'Humbucker + two singlecoils'), ('OTH', 'Other'), ('NON', 'No pickups')], max_length=3, null=True),
        ),
    ]
