# Generated by Django 4.2.2 on 2023-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0019_remove_image_guitar_remove_rent_related_gear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='transaction_type',
            field=models.CharField(choices=[('S', 'Sell'), ('E', 'Exchange'), ('R', 'Rent')], default='S', max_length=1),
        ),
    ]
