# Generated by Django 4.2.2 on 2023-07-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_guitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
