# Generated by Django 4.2.2 on 2023-07-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gear', '0019_remove_image_guitar_remove_rent_related_gear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('more_info', models.TextField(verbose_name='More informations')),
                ('related_gear', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gear.guitar')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('renting_time', models.IntegerField(blank=True, null=True, verbose_name='Renting time in days')),
                ('more_info', models.TextField(verbose_name='More informations')),
                ('related_gear', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gear.guitar')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('guitar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.guitar')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('more_info', models.TextField(verbose_name='More informations')),
                ('related_gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_for', to='gear.guitar')),
            ],
        ),
    ]
