# Generated by Django 4.2.2 on 2023-07-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0002_remove_message_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
